# ->->->->-> Primary <-<-<-<-<-
arch: "mini"
result_dir: "./trained_models"
exp_name: "test_mini_BiPK0.1"
exp_mode: "prune"
normalize: False
scaled_score_init: True

k: 0.1 

# ->->->->-> Train <-<-<-<-<-
trainer: "bilevel_corrected_mini"
layer_type: "unstructured"
epochs: 1
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0001
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1


# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: MINI
batch_size: 1
test_batch_size: 1
num_classes: 1
image_dim: 1
data_dir: "./data"

# ->->->->-> Misc <-<-<-<-<-
seed: 1234
print_freq: 100

# ->->->->-> Bi-level <-<-<-<-<-
lr2: 0.0001
mask_lr_schedule: step
mask_lr: 0.1