arch: "resnet20s"
exp_name: "EMNIST_resnet20s_Pretrain"
result_dir: "./trained_models"
exp_mode: "pretrain"
layer_type: "dense"
normalize: True

# ->->->->-> Train <-<-<-<-<-
trainer: "base"
epochs: 200
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0005
momentum: 0.9
warmup_epochs: 0
warmup_lr: 0.1

# ->->->->-> Eval <-<-<-<-<-
val_method: base

# ->->->->-> Dataset <-<-<-<-<-
dataset: EMNIST
batch_size: 128
test_batch_size: 128
num_classes: 47  # Adjust the number of classes based on EMNIST split
image_dim: 28  # Adjust the image dimensions based on EMNIST dataset
data_dir: "./data"

# ->->->->-> Misc <-<-<-<-<-
seed: 1234
print_freq: 100
