# ->->->->-> Primary <-<-<-<-<-
arch: "mnist_model"
result_dir: "./trained_models"
exp_name: "MNIST_mnist_model_Penalized_Bilevel_1"
exp_mode: "prune"
normalize: True
scaled_score_init: True

#k: 0.1 no k here but a lambda and alpha

# ->->->->-> Train <-<-<-<-<-
trainer: "penalized_bilevel_1"
layer_type: "unstructured"
epochs: 1
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0001
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1

#hyperparameters of penalty term
lambd : 100
alpha : 10


# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: MNIST
batch_size: 128
test_batch_size: 128
num_classes: 10
image_dim: 32
data_dir: "./data"

# ->->->->-> Misc <-<-<-<-<-
seed: 1234
print_freq: 100

# ->->->->-> Bi-level <-<-<-<-<-
lr2: 0.0001
mask_lr_schedule: step
mask_lr: 0.1