# ->->->->-> Primary <-<-<-<-<-
arch: "mnist_model"
result_dir: "./trained_models"
exp_name: "MNIST_mnist_model_BiPK0.1"
exp_mode: "prune"
normalize: True
scaled_score_init: True

k: 0.1 

# ->->->->-> Train <-<-<-<-<-
trainer: "bilevel_baseline"
layer_type: "unstructured"
epochs: 100
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0001
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1


# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: KMNIST
batch_size: 64
test_batch_size: 64
data_dir: "./data"
num_classes: 10
image_dim: 28

# ->->->->-> Misc <-<-<-<-<-
seed: 1234
print_freq: 100

# ->->->->-> Bi-level <-<-<-<-<-
lr2: 0.0001
mask_lr_schedule: step
mask_lr: 0.1